server:
  port: 8010
  servlet:
    context-path: /

spring:
  redis:
    host: 192.168.31.234 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://192.168.31.234:5432/ai?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: postgres
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true
      max-request-size: 50MB

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.ai.website: debug


logstash:
  host: logstash



####################### 192.168.31.234 Linux  #######################
web:
  root-path: /portal/upload/
  ip-address: http://192.168.31.234

  #上传头像图片地址
  image-path: /images/
  #上传附件地址
  file-path: /files/



